###############################################################################
# RebelEspresso Firmware — Build Orchestration
#
# Build runs inside Docker. Flash and monitor run on the host using esptool
# and the build tree's flash_args (generated by ESP-IDF, no hardcoded addresses).
###############################################################################

# Project configuration
BUILD_STAGE  ?= dev
BUILD_TYPE   ?= Release
BUILD_DIR    ?= build

# Serial port — auto-detected if not specified
BAUD ?= 2000000
PORT ?= $(shell find /dev -name 'cu.usbserial*' -o -name 'cu.SLAB_USB*' -o -name 'cu.wchusbserial*' 2>/dev/null | head -1)

# Docker
DOCKER_COMPOSE = docker compose
DOCKER_RUN     = $(DOCKER_COMPOSE) run --rm idf

# CMake variables forwarded to idf.py
CMAKE_VARS = \
	-DBUILD_STAGE=$(BUILD_STAGE) \
	-DCMAKE_BUILD_TYPE=$(BUILD_TYPE)

# Sentinel file tracking when the Docker image was last built.
# Rebuilds only when Dockerfile, requirements, or constraints change.
.docker-image: Dockerfile requirements.txt constraints.txt
	$(DOCKER_COMPOSE) build
	@touch .docker-image

###############################################################################
# Build (Docker)
###############################################################################

.PHONY: build test lint format clean fullclean menuconfig shell setup submodules docker webapp sdkconfig-sync

# idf.py only seeds sdkconfig from sdkconfig.defaults when sdkconfig is ABSENT;
# a stale sdkconfig silently overrides later edits to the defaults (and even
# `idf.py fullclean` keeps it). Regenerate whenever the *content* of
# sdkconfig.defaults changes or sdkconfig is missing. Content hashing is used
# instead of mtime (`-nt`): a build touches sdkconfig, which can make it newer
# than a subsequent defaults edit and silently skip the re-seed.
SDKCONFIG_HASH_FILE = .sdkconfig.defaults.hash
sdkconfig-sync:
	@cur=$$( (shasum -a 256 sdkconfig.defaults 2>/dev/null || sha256sum sdkconfig.defaults) | awk '{print $$1}'); \
	prev=$$(cat $(SDKCONFIG_HASH_FILE) 2>/dev/null); \
	if [ ! -f sdkconfig ] || [ "$$cur" != "$$prev" ]; then \
		echo "sdkconfig.defaults changed — regenerating sdkconfig from defaults"; \
		rm -f sdkconfig sdkconfig.old; \
		echo "$$cur" > $(SDKCONFIG_HASH_FILE); \
	fi

## Build firmware (includes embedded web UI)
build: .docker-image sdkconfig-sync
	$(DOCKER_RUN) idf.py $(CMAKE_VARS) build

## Run unit tests in QEMU
test: .docker-image
	$(DOCKER_RUN) bash -c "cd test_app && idf.py build && rm -f build/qemu_flash.bin && /workspace/test_app/run_qemu.sh"

## Static analysis with clang-tidy (requires build first for compile_commands.json)
lint: .docker-image
	$(DOCKER_RUN) /workspace/scripts/lint.sh

## Lint with auto-fix
lint-fix: .docker-image
	$(DOCKER_RUN) /workspace/scripts/lint.sh --fix

## Format source files with clang-format
format: .docker-image
	$(DOCKER_RUN) bash -c "find components/rebel-espresso/src components/esp-connectivity/src main \
		-name '*.cpp' -o -name '*.c' -o -name '*.h' | xargs clang-format -i"

## Check formatting (dry-run, exits non-zero if changes needed)
format-check: .docker-image
	$(DOCKER_RUN) bash -c "find components/rebel-espresso/src components/esp-connectivity/src main \
		-name '*.cpp' -o -name '*.c' -o -name '*.h' | xargs clang-format --dry-run --Werror"

## Clean build artifacts
clean:
	$(DOCKER_RUN) idf.py fullclean

## Full clean including managed components and test build
fullclean:
	$(DOCKER_RUN) bash -c "idf.py fullclean && rm -rf managed_components test_app/build"

## Interactive menuconfig
menuconfig: .docker-image
	$(DOCKER_COMPOSE) run --rm -it idf idf.py menuconfig

## Shell inside the build container
shell: .docker-image
	$(DOCKER_COMPOSE) run --rm -it idf bash

###############################################################################
# Flash and Monitor (host — uses build tree's flash_args, no hardcoded addresses)
###############################################################################

.PHONY: flash flash-app monitor

## Flash everything (firmware + bootloader + partition table)
flash:
	cd $(BUILD_DIR) && esptool.py --chip esp32 -p $(PORT) -b $(BAUD) \
		--before default_reset --after hard_reset write_flash \
		$$(sed '1d' flash_args)

## Flash firmware only (preserves NVS config)
flash-app:
	cd $(BUILD_DIR) && esptool.py --chip esp32 -p $(PORT) -b $(BAUD) \
		--before default_reset --after hard_reset write_flash \
		$$(sed '1d' flash_app_args)

## Serial monitor
monitor:
	python3 -m serial.tools.miniterm --raw $(PORT) 115200

###############################################################################
# Web UI (development only — production UI is embedded in firmware)
###############################################################################

## Run web UI locally with mock API (for development)
webapp-dev:
	@python3 webapp/dev-server.py

###############################################################################
# Setup
###############################################################################

## First-time setup: submodules + Docker image + hooks
setup: submodules .docker-image setup-hooks

## Force rebuild the Docker image
docker:
	$(DOCKER_COMPOSE) build
	@touch .docker-image

## Init/update git submodules
submodules:
	git submodule update --init --recursive

## Install git hooks
setup-hooks:
	@cp scripts/pre-commit .git/hooks/pre-commit
	@chmod +x .git/hooks/pre-commit
	@echo "Pre-commit hook installed."
