steps:
  # See https://cloud.google.com/cloud-build/docs/access-private-github-repos
  # Also need 'gcloud config set gcloudignore/enabled false'
  # and don't forget to add a .gcloudignore file with "!.git" in it
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=github-rsa-key > /root/.ssh/id_github' ]
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  # Set up git with key and domain
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_github
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_github
        EOF
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # checkout git submodules
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git init
        git remote add origin git@github.com:/lerebel103/$REPO_NAME.git
        git branch --set-upstream-to=origin/$BRANCH_NAME $BRANCH_NAME
        git pull --tags
        git fetch --depth=1000 origin $COMMIT_SHA
        git submodule update --init --recursive
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Now build project
  - name: 'gcr.io/$PROJECT_ID/rebelespresso-fw-build:latest'
    args: ['bash', 'ci/build.sh']
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Place artifacts on GS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'build/firmware/*/', 'gs://rebelthings-firmware/release']
